name: Build documentation

"on":
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/4c-multiphysics/4c-minimal:main
      options: --user root --env OMPI_ALLOW_RUN_AS_ROOT=1 --env OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-queens-pixi
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          environments: dev
          activate-environment: dev
      - name: Create links to 4C
        run: |
          ln -s /home/user/4C/bin/ config/4C_build
      - name: Register Jupyter kernel
        run: |
          python -m ipykernel install --user --name queens --display-name "Python (queens)"
      - name: Install xvfb
        run: |
          apt-get update
          apt-get install -y xvfb
      - name: Sphinx build
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          set -x
          sphinx-apidoc -o doc/source src/ -fMT
          cd doc
          xvfb-run -a sphinx-build -b html -d build/doctrees source build/html -W
      - name: Upload html
        uses: actions/upload-pages-artifact@v5
        with:
          path: doc/build/html
          retention-days: 1

  deploy-documentation:
    name: Deploy documentation
    needs: build-documentation
    if: ${{github.ref == 'refs/heads/main'}}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
