# yamllint disable
name: Testsuite

on:
  schedule:
    - cron: "0 1 * * *"
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  # Set TEST_TIMING_OPTION if local test should be timed. Default is off.
  TEST_TIMING_OPTION: ""

jobs:
  run_tests_core:
    name: core tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            pytest_markers: "unit_tests or integration_tests"
          - os: macos-latest
            pytest_markers: "unit_tests or integration_tests"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-queens-pixi
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          environments: queens-dev
          activate-environment: queens-dev
      - name: Run pytest for unit tests and integration tests
        run: |
          set -euo pipefail

          COVERAGE_FILE=".coverage.core.${{ runner.os }}" pytest -v -m "${{ matrix.pytest_markers }}" --cov --cov-report=term $TEST_TIMING_OPTION --color=yes -o junit_logging=all --junitxml=test_junit_core_${{ runner.os }}.xml
      - name: Upload raw core test reports
        if: success() || failure()
        uses: actions/upload-artifact@v7
        with:
          name: raw-test-reports-core-${{ runner.os }}
          include-hidden-files: true
          path: |
            .coverage.core.${{ runner.os }}
            test_junit_core_${{ runner.os }}.xml
          if-no-files-found: error
          retention-days: 7

  run_tests_tutorials:
    name: tutorial tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-queens-pixi
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          environments: queens-dev
          activate-environment: queens-dev
      - name: Run pytest for tutorial tests
        run: |
          set -euo pipefail

          COVERAGE_FILE=".coverage.tutorials.${{ runner.os }}" pytest -v -m "tutorial_tests" --cov --cov-report=term $TEST_TIMING_OPTION --color=yes -o junit_logging=all --junitxml=test_junit_tutorials_${{ runner.os }}.xml
      - name: Upload raw tutorial test reports
        if: success() || failure()
        uses: actions/upload-artifact@v7
        with:
          name: raw-test-reports-tutorials-${{ runner.os }}
          include-hidden-files: true
          path: |
            .coverage.tutorials.${{ runner.os }}
            test_junit_tutorials_${{ runner.os }}.xml
          if-no-files-found: error
          retention-days: 7

  run_tests_fourc:
    name: 4C integration tests (ubuntu-latest)
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/4c-multiphysics/4c-minimal:main
      options: --user root --env OMPI_ALLOW_RUN_AS_ROOT=1 --env OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-queens-pixi
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          environments: queens-dev
          activate-environment: queens-dev
      - name: Create links to 4C
        run: |
          ln -s /home/user/4C/bin/ config/4C_build
      - name: Run pytest for 4C integration tests
        run: |
          set -euo pipefail

          COVERAGE_FILE=".coverage.fourc.${{ runner.os }}" pytest -v -m "integration_tests_fourc" --cov --cov-report=term $TEST_TIMING_OPTION --color=yes -o junit_logging=all --junitxml=test_junit_fourc_${{ runner.os }}.xml
      - name: Upload raw 4C test reports
        if: success() || failure()
        uses: actions/upload-artifact@v7
        with:
          name: raw-test-reports-fourc-${{ runner.os }}
          include-hidden-files: true
          path: |
            .coverage.fourc.${{ runner.os }}
            test_junit_fourc_${{ runner.os }}.xml
          if-no-files-found: error
          retention-days: 7

  run_tests_tutorials_fourc:
    name: 4C tutorial tests (ubuntu-latest)
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/4c-multiphysics/4c-minimal:main
      options: --user root --env OMPI_ALLOW_RUN_AS_ROOT=1 --env OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-queens-pixi
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          environments: queens-dev
          activate-environment: queens-dev
      - name: Create links to 4C
        run: |
          ln -s /home/user/4C/bin/ config/4C_build
      - name: Run pytest for 4C tutorial tests
        run: |
          set -euo pipefail

          COVERAGE_FILE=".coverage.tutorials_fourc.${{ runner.os }}" pytest -v -m "tutorial_tests_fourc" --cov --cov-report=term $TEST_TIMING_OPTION --color=yes -o junit_logging=all --junitxml=test_junit_tutorials_fourc_${{ runner.os }}.xml
      - name: Upload raw 4C tutorial test reports
        if: success() || failure()
        uses: actions/upload-artifact@v7
        with:
          name: raw-test-reports-tutorials-fourc-${{ runner.os }}
          include-hidden-files: true
          path: |
            .coverage.tutorials_fourc.${{ runner.os }}
            test_junit_tutorials_fourc_${{ runner.os }}.xml
          if-no-files-found: error
          retention-days: 7

  report_test_results:
    name: report test results
    if: always()
    runs-on: ubuntu-latest
    needs:
      - run_tests_core
      - run_tests_tutorials
      - run_tests_fourc
      - run_tests_tutorials_fourc
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-queens-pixi
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          environments: queens-dev
          activate-environment: queens-dev
          ensure-rsync: false
      - name: Download raw core test reports from Ubuntu
        uses: actions/download-artifact@v8
        with:
          name: raw-test-reports-core-Linux
          path: reports/core-ubuntu
      - name: Download raw core test reports from macOS
        uses: actions/download-artifact@v8
        with:
          name: raw-test-reports-core-macOS
          path: reports/core-macos
      - name: Download raw tutorial test reports from Ubuntu
        uses: actions/download-artifact@v8
        with:
          name: raw-test-reports-tutorials-Linux
          path: reports/tutorials-ubuntu
      - name: Download raw tutorial test reports from macOS
        uses: actions/download-artifact@v8
        with:
          name: raw-test-reports-tutorials-macOS
          path: reports/tutorials-macos
      - name: Download raw 4C test reports
        uses: actions/download-artifact@v8
        with:
          name: raw-test-reports-fourc-Linux
          path: reports/fourc-ubuntu
      - name: Download raw 4C tutorial test reports
        uses: actions/download-artifact@v8
        with:
          name: raw-test-reports-tutorials-fourc-Linux
          path: reports/tutorials-fourc-ubuntu
      - name: Combine Ubuntu coverage data and build reports
        run: |
          set -euo pipefail

          cp reports/core-ubuntu/.coverage.core.Linux .coverage.core.Linux
          cp reports/tutorials-ubuntu/.coverage.tutorials.Linux .coverage.tutorials.Linux
          cp reports/fourc-ubuntu/.coverage.fourc.Linux .coverage.fourc.Linux
          cp reports/tutorials-fourc-ubuntu/.coverage.tutorials_fourc.Linux .coverage.tutorials_fourc.Linux

          pixi run --locked -e queens-dev coverage combine .coverage.core.Linux .coverage.tutorials.Linux .coverage.fourc.Linux .coverage.tutorials_fourc.Linux
          pixi run --locked -e queens-dev coverage html -d html_coverage_report
          pixi run --locked -e queens-dev coverage xml -o xml_coverage_report.xml
          pixi run --locked -e queens-dev coverage report

          python .github/xml_summaries_to_md.py \
            reports/core-ubuntu/test_junit_core_Linux.xml \
            xml_coverage_report.xml >> "$GITHUB_STEP_SUMMARY"
      - name: Publish combined junit pytest report
        if: success() || failure()
        uses: mikepenz/action-junit-report@v6
        with:
          report_paths: "reports/**/*.xml"
          annotate_only: true
          job_summary: false
      - name: Upload combined coverage report
        uses: actions/upload-pages-artifact@v5
        with:
          name: html-coverage-report
          path: html_coverage_report/
          retention-days: 7
